# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0c814f014c0f912012209ef495a71a71149dd3645e5a02a32b59c000129d17db0122e9e714ddd3ac99554373104a9c2e17c76397aad58bdce23b81f369802f3

test:
  secret_key_base: 9a4e680e55651d57d1d0e1cc72d03584609ce6739967345af23cb009cc88e2207fa9f38669224c330823b4dc00ca3366d47afb210909140485efcf55434c1877

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
